<template>
    <div class="goods-category">
        <el-card class="!border-none" shadow="never"><el-form :model="filters" inline class="filter-form"><el-form-item label="分类名称"><el-input v-model="filters.keyword" clearable placeholder="请输入分类名称" @keyup.enter="resetPage" /></el-form-item><el-form-item label="分类状态"><el-select v-model="filters.status" clearable placeholder="全部状态"><el-option label="显示" value="显示" /><el-option label="隐藏" value="隐藏" /></el-select></el-form-item><el-form-item><el-button type="primary" @click="resetPage">查询</el-button><el-button @click="resetFilters">重置</el-button></el-form-item></el-form></el-card>
        <el-card class="!border-none mt-4" shadow="never"><div class="toolbar"><el-button type="primary" :icon="Plus" @click="openForm()">添加分类</el-button><span>共 {{ filteredCategories.length }} 个分类</span></div><el-table :data="pagedCategories" size="large" stripe table-layout="fixed" class="category-table"><el-table-column label="ID" prop="id" min-width="180" class-name="first-column" label-class-name="first-column" /><el-table-column label="分类名称" prop="name" min-width="180" /><el-table-column label="排序" prop="sort" min-width="180" /><el-table-column label="状态" min-width="180"><template #default="{ row }"><el-switch v-model="row.visible" @change="changeVisible(row)" /></template></el-table-column><el-table-column label="操作" min-width="180" class-name="last-column" label-class-name="last-column"><template #default="{ row }"><el-button type="primary" link @click="openForm(row)">编辑</el-button><el-button type="danger" link @click="removeCategory(row)">删除</el-button></template></el-table-column></el-table><div class="flex justify-end mt-4"><el-pagination v-model:current-page="page" background layout="total, prev, pager, next" :total="filteredCategories.length" /></div></el-card>
        <el-dialog v-model="formVisible" :title="editingId ? '编辑分类' : '添加分类'" width="480px" destroy-on-close><el-form ref="formRef" :model="form" :rules="rules" label-width="82px"><el-form-item label="分类名称" prop="name"><el-input v-model="form.name" placeholder="请输入分类名称" /></el-form-item><el-form-item label="分类排序"><el-input-number v-model="form.sort" :min="0" class="!w-full" /></el-form-item><el-form-item label="分类状态"><el-radio-group v-model="form.visible"><el-radio :value="true">显示</el-radio><el-radio :value="false">隐藏</el-radio></el-radio-group></el-form-item></el-form><template #footer><el-button @click="formVisible = false">取消</el-button><el-button type="primary" @click="saveCategory">确定</el-button></template></el-dialog>
    </div>
</template>

<script lang="ts" setup name="goodsCategory">
import { Plus } from '@element-plus/icons-vue'
import type { FormInstance, FormRules } from 'element-plus'
import { ElMessageBox } from 'element-plus'
interface Category { id: string; name: string; sort: number; visible: boolean }
const categoryList = reactive<Category[]>([{ id: 'GC1001', name: '饮料', sort: 100, visible: true }, { id: 'GC1002', name: '休闲食品', sort: 90, visible: true }, { id: 'GC1003', name: '日用百货', sort: 80, visible: true }, { id: 'GC1004', name: '礼品礼盒', sort: 70, visible: false }, { id: 'GC1005', name: '新品专区', sort: 60, visible: true }, { id: 'GC1006', name: '节日精选', sort: 50, visible: false }])
const filters = reactive({ keyword: '', status: '' }); const page = ref(1); const pageSize = 10; const formVisible = ref(false); const editingId = ref(''); const formRef = ref<FormInstance>(); const form = reactive({ name: '', sort: 0, visible: true }); const rules: FormRules = { name: [{ required: true, message: '请输入分类名称', trigger: 'blur' }] }
const filteredCategories = computed(() => categoryList.filter((item) => (!filters.keyword.trim() || item.name.includes(filters.keyword.trim())) && (!filters.status || (filters.status === '显示') === item.visible)))
const pagedCategories = computed(() => filteredCategories.value.slice((page.value - 1) * pageSize, page.value * pageSize))
const resetPage = () => { page.value = 1 }; const resetFilters = () => { filters.keyword = ''; filters.status = ''; resetPage() }
const changeVisible = (item: Category) => ElMessage.success(`分类已${item.visible ? '显示' : '隐藏'}`)
const openForm = (item?: Category) => { editingId.value = item?.id || ''; Object.assign(form, item ? { name: item.name, sort: item.sort, visible: item.visible } : { name: '', sort: 0, visible: true }); formVisible.value = true }
const saveCategory = async () => { if (!formRef.value || !(await formRef.value.validate().catch(() => false))) return; if (editingId.value) { const item = categoryList.find((category) => category.id === editingId.value); if (item) Object.assign(item, form) } else categoryList.unshift({ ...form, id: `GC${1001 + categoryList.length}` }); formVisible.value = false; ElMessage.success(editingId.value ? '分类已更新' : '分类已添加') }
const removeCategory = async (item: Category) => { await ElMessageBox.confirm(`确定删除分类“${item.name}”吗？`, '删除分类', { type: 'warning' }); const index = categoryList.findIndex((category) => category.id === item.id); categoryList.splice(index, 1); ElMessage.success('分类已删除') }
</script>

<style lang="scss" scoped>
.filter-form { margin-bottom: -18px; }.filter-form :deep(.el-input), .filter-form :deep(.el-select) { width: 240px; }.toolbar { display: flex; align-items: center; justify-content: space-between; margin-bottom: 16px; }.toolbar span { color: var(--el-text-color-secondary); font-size: 13px; }.category-table :deep(.el-table__cell) { padding: 14px 0; }.category-table :deep(.first-column .cell) { padding-left: 16px; }.category-table :deep(.last-column .cell) { padding-right: 16px; }@media (max-width: 640px) { .filter-form :deep(.el-input), .filter-form :deep(.el-select) { width: 100%; }.filter-form :deep(.el-form-item) { width: 100%; margin-right: 0; } }
</style>
